source("getPowerConsumptionData.R")
getPowerConsumptionData()
png("plot3.png")
plot(as.POSIXlt(power_consumption$Date),  power_consumption$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", col="black")
lines(as.POSIXlt(power_consumption$Date), power_consumption$Sub_metering_2, col="red")
lines(as.POSIXlt(power_consumption$Date), power_consumption$Sub_metering_3, col="blue")
legend("topright", lty=c(1,1), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()