source("getPowerConsumptionData.R")
getPowerConsumptionData()
png("plot4.png")
par(mfrow=c(2,2))
plot(as.POSIXlt(power_consumption$Date),  power_consumption$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(as.POSIXlt(power_consumption$Date),  power_consumption$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(as.POSIXlt(power_consumption$Date),  power_consumption$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", col="black")
lines(as.POSIXlt(power_consumption$Date), power_consumption$Sub_metering_2, col="red")
lines(as.POSIXlt(power_consumption$Date), power_consumption$Sub_metering_3, col="blue")
legend("topright", lty=c(1,1), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot( as.POSIXlt(power_consumption$Date),  power_consumption$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()